//! Firewall management for jail port forwarding.
//!
//! Uses PF anchors to manage RDR rules without modifying the host's `pf.conf`.
//! Forward definitions are persisted so separate CLI invocations can list,
//! update, and remove them consistently.

use crate::error::{Error, Result};
use serde::{Deserialize, Serialize};
use std::net::IpAddr;
use std::path::{Path, PathBuf};
use std::process::Command;

/// PF anchor name for blackship rules.
const PF_ANCHOR: &str = "blackship";

/// Enable PF on the host: write a minimal /etc/pf.conf carrying the
/// blackship anchors if none exists, persist pf_enable=YES, and start pf.
pub fn enable_pf() -> Result<()> {
    let running = Command::new("/sbin/pfctl")
        .args(["-s", "info"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if running {
        return Ok(());
    }

    let pf_conf = Path::new("/etc/pf.conf");
    if !pf_conf.exists() {
        let conf = format!(
            "# Generated by blackship setup --enable-pf\n\
             set skip on lo0\n\
             nat-anchor \"{a}/*\"\n\
             rdr-anchor \"{a}/*\"\n\
             anchor \"{a}/*\"\n\
             pass all\n",
            a = PF_ANCHOR
        );
        std::fs::write(pf_conf, conf)
            .map_err(|e| Error::Network(format!("Failed to write /etc/pf.conf: {}", e)))?;
        println!("Wrote minimal /etc/pf.conf with blackship anchors (default: pass all)");
    }

    let status = Command::new("/usr/sbin/sysrc")
        .arg("pf_enable=YES")
        .status()
        .map_err(|e| Error::Network(format!("Failed to run sysrc: {}", e)))?;
    if !status.success() {
        return Err(Error::Network("sysrc pf_enable=YES failed".to_string()));
    }

    let status = Command::new("/usr/sbin/service")
        .args(["pf", "start"])
        .status()
        .map_err(|e| Error::Network(format!("Failed to start pf: {}", e)))?;
    if !status.success() {
        return Err(Error::Network(
            "service pf start failed; check /etc/pf.conf".to_string(),
        ));
    }
    println!("PF enabled and started.");
    Ok(())
}

/// Port forwarding rule.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PortForward {
    /// External port to listen on.
    pub external_port: u16,
    /// Internal (jail) port to forward to.
    pub internal_port: u16,
    /// Protocol (tcp, udp).
    pub protocol: String,
    /// Jail IP address.
    pub jail_ip: IpAddr,
    /// Bind to specific external IP (None = all interfaces).
    pub bind_ip: Option<IpAddr>,
    /// Jail name (for identification).
    pub jail_name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct PortForwardFile {
    forwards: Vec<PortForward>,
}

impl PortForward {
    /// Create a new port forward rule.
    pub fn new(
        external_port: u16,
        internal_port: u16,
        protocol: &str,
        jail_ip: IpAddr,
        jail_name: &str,
    ) -> Self {
        Self {
            external_port,
            internal_port,
            protocol: protocol.to_string(),
            jail_ip,
            bind_ip: None,
            jail_name: jail_name.to_string(),
        }
    }

    /// Bind to a specific external IP.
    pub fn with_bind_ip(mut self, ip: IpAddr) -> Self {
        self.bind_ip = Some(ip);
        self
    }

    /// Generate PF RDR rule; errors unless the protocol is `tcp` or `udp`.
    pub fn to_pf_rule(&self) -> Result<String> {
        match self.protocol.as_str() {
            "tcp" | "udp" => {}
            other => {
                return Err(Error::ConfigValidation(format!(
                    "invalid protocol {:?}: must be \"tcp\" or \"udp\"",
                    other
                )));
            }
        }

        let bind = match &self.bind_ip {
            Some(ip) => format!("on {} ", ip),
            None => String::new(),
        };

        // A newline in the comment would inject a new PF rule.
        let safe_name: String = self
            .jail_name
            .chars()
            .map(|c| {
                if c.is_alphanumeric() || c == '-' || c == '_' || c == '.' {
                    c
                } else {
                    '_'
                }
            })
            .collect();

        Ok(format!(
            "rdr {}proto {} from any to any port {} -> {} port {} # jail:{}",
            bind, self.protocol, self.external_port, self.jail_ip, self.internal_port, safe_name
        ))
    }
}

/// Bulkhead manager for PF.
#[derive(Debug, Default)]
pub struct BulkheadManager {
    /// Active port forwards.
    forwards: Vec<PortForward>,
    /// Optional persistence path for forward definitions.
    state_path: Option<PathBuf>,
}

impl BulkheadManager {
    /// Create an in-memory bulkhead manager.
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a bulkhead manager backed by a state file under `data_dir`.
    pub fn from_data_dir(data_dir: &Path) -> Result<Self> {
        let state_path = data_dir.join("port-forwards.toml");
        let forwards = read_forwards(&state_path)?;
        Ok(Self {
            forwards,
            state_path: Some(state_path),
        })
    }

    /// Initialize the PF anchor.
    ///
    /// The host's `pf.conf` must include:
    /// ```text
    /// rdr-anchor "blackship"
    /// anchor "blackship"
    /// ```
    pub fn init() -> Result<()> {
        let output = Command::new("/sbin/pfctl")
            .args(["-s", "info"])
            .output()
            .map_err(|e| Error::Network(format!("Failed to check PF status: {}", e)))?;

        if !output.status.success() {
            return Err(Error::Network(
                "PF is not running. Enable it with: service pf start".to_string(),
            ));
        }

        let output = Command::new("/sbin/pfctl")
            .args(["-a", PF_ANCHOR, "-s", "rules"])
            .output()
            .map_err(|e| Error::Network(format!("Failed to check anchor: {}", e)))?;

        if !output.status.success() {
            eprintln!("Warning: PF anchor '{}' may not be configured.", PF_ANCHOR);
            eprintln!("Add these lines to /etc/pf.conf:");
            eprintln!("  rdr-anchor \"{}\"", PF_ANCHOR);
            eprintln!("  anchor \"{}\"", PF_ANCHOR);
        }

        Ok(())
    }

    /// Re-apply the currently persisted rules to PF.
    pub fn sync_rules(&self) -> Result<()> {
        Self::init()?;
        self.apply_rules()
    }

    /// Add a port forward rule.
    pub fn add_forward(&mut self, forward: PortForward) -> Result<()> {
        Self::init()?;

        if self.forwards.iter().any(|existing| existing == &forward) {
            return Ok(());
        }

        if let Some(existing) = self.forwards.iter().find(|existing| {
            existing.bind_ip == forward.bind_ip
                && existing.protocol == forward.protocol
                && existing.external_port == forward.external_port
        }) {
            return Err(Error::Network(format!(
                "Port {} {}/{} is already exposed for jail '{}'",
                existing.external_port,
                existing
                    .bind_ip
                    .map(|ip| ip.to_string())
                    .unwrap_or_else(|| "*".into()),
                existing.protocol,
                existing.jail_name
            )));
        }

        self.forwards.push(forward);
        self.forwards.sort_by(|a, b| {
            a.jail_name
                .cmp(&b.jail_name)
                .then_with(|| a.protocol.cmp(&b.protocol))
                .then_with(|| a.external_port.cmp(&b.external_port))
        });
        self.persist()?;
        self.apply_rules()
    }

    /// Remove port forwards for a jail.
    pub fn remove_jail_forwards(&mut self, jail_name: &str) -> Result<()> {
        Self::init()?;
        self.forwards
            .retain(|forward| forward.jail_name != jail_name);
        self.persist()?;
        self.apply_rules()
    }

    /// List current port forwards.
    pub fn list_forwards(&self) -> &[PortForward] {
        &self.forwards
    }

    /// Get forwards for a specific jail.
    pub fn get_jail_forwards(&self, jail_name: &str) -> Vec<&PortForward> {
        self.forwards
            .iter()
            .filter(|forward| forward.jail_name == jail_name)
            .collect()
    }

    fn persist(&self) -> Result<()> {
        let Some(path) = self.state_path.as_ref() else {
            return Ok(());
        };

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| {
                Error::Network(format!("Failed to create port-forward state dir: {}", e))
            })?;
        }

        write_forwards(path, &self.forwards)
    }

    fn apply_rules(&self) -> Result<()> {
        let rules: Vec<String> = self
            .forwards
            .iter()
            .map(|forward| forward.to_pf_rule())
            .collect::<Result<Vec<String>>>()?;
        let rules_text = rules.join("\n");

        let mut child = Command::new("/sbin/pfctl")
            .args(["-a", PF_ANCHOR, "-f", "-"])
            .stdin(std::process::Stdio::piped())
            .spawn()
            .map_err(|e| Error::Network(format!("Failed to run pfctl: {}", e)))?;

        if let Some(stdin) = child.stdin.as_mut() {
            use std::io::Write;
            stdin
                .write_all(rules_text.as_bytes())
                .map_err(|e| Error::Network(format!("Failed to write rules: {}", e)))?;
        }

        let output = child
            .wait_with_output()
            .map_err(|e| Error::Network(format!("Failed to wait for pfctl: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(Error::Network(format!("pfctl failed: {}", stderr)));
        }

        Ok(())
    }
}

fn read_forwards(path: &Path) -> Result<Vec<PortForward>> {
    if !path.exists() {
        return Ok(Vec::new());
    }

    let state: PortForwardFile = crate::atomic::read_toml(path, "port-forward state")?;
    Ok(state.forwards)
}

fn write_forwards(path: &Path, forwards: &[PortForward]) -> Result<()> {
    crate::atomic::write_toml_atomic(
        path,
        &PortForwardFile {
            forwards: forwards.to_vec(),
        },
        "port-forward state",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_dir() -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("blackship-bulkhead-{}", unique))
    }

    #[test]
    fn test_port_forward_rule() {
        let forward = PortForward::new(8080, 80, "tcp", "10.0.1.10".parse().unwrap(), "webserver");

        let rule = forward.to_pf_rule().unwrap();
        assert!(rule.contains("rdr"));
        assert!(rule.contains("proto tcp"));
        assert!(rule.contains("port 8080"));
        assert!(rule.contains("-> 10.0.1.10"));
        assert!(rule.contains("port 80"));
        assert!(rule.contains("# jail:webserver"));
    }

    #[test]
    fn test_port_forward_with_bind_ip() {
        let forward = PortForward::new(443, 443, "tcp", "10.0.1.10".parse().unwrap(), "webserver")
            .with_bind_ip("192.168.1.100".parse().unwrap());

        let rule = forward.to_pf_rule().unwrap();
        assert!(rule.contains("on 192.168.1.100"));
    }

    #[test]
    fn test_port_forward_invalid_protocol() {
        let forward = PortForward::new(8080, 80, "icmp", "10.0.1.10".parse().unwrap(), "webserver");
        assert!(forward.to_pf_rule().is_err());

        let injected = PortForward::new(
            8080,
            80,
            "tcp from any to any\npass all",
            "10.0.1.10".parse().unwrap(),
            "webserver",
        );
        assert!(injected.to_pf_rule().is_err());
    }

    #[test]
    fn test_port_forward_udp_protocol() {
        let forward = PortForward::new(53, 53, "udp", "10.0.1.10".parse().unwrap(), "dns");
        let rule = forward.to_pf_rule().unwrap();
        assert!(rule.contains("proto udp"));
    }

    #[test]
    fn test_port_forward_creation() {
        let forward = PortForward::new(3000, 3000, "tcp", "10.0.1.5".parse().unwrap(), "myjail");

        assert_eq!(forward.external_port, 3000);
        assert_eq!(forward.internal_port, 3000);
        assert_eq!(forward.jail_name, "myjail");
        assert_eq!(forward.protocol, "tcp");
    }

    #[test]
    fn test_bulkhead_manager() {
        let manager = BulkheadManager::new();
        assert_eq!(manager.list_forwards().len(), 0);
    }

    #[test]
    fn test_bulkhead_state_round_trip() {
        let root = temp_dir();
        std::fs::create_dir_all(&root).unwrap();

        let state_path = root.join("port-forwards.toml");
        write_forwards(
            &state_path,
            &[PortForward::new(
                8080,
                80,
                "tcp",
                "10.0.1.10".parse().unwrap(),
                "demo-web",
            )],
        )
        .unwrap();

        let manager = BulkheadManager::from_data_dir(&root).unwrap();
        assert_eq!(manager.list_forwards().len(), 1);
        assert_eq!(manager.list_forwards()[0].jail_name, "demo-web");
        assert_eq!(
            manager.list_forwards()[0].jail_ip,
            "10.0.1.10".parse::<IpAddr>().unwrap()
        );

        std::fs::remove_dir_all(root).unwrap();
    }
}
